/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package snebookstoreinventorymanagement;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class FunctionSelect extends javax.swing.JFrame {

    /**
     * Creates new form FunctionSelect
     */
    
    Color DefaultColor,ClickedColor,TouchColor;
 
    public FunctionSelect() 
    {
        initComponents();
        DefaultColor = new Color(0,0,204);
        ClickedColor = new Color(242,242,242);
        TouchColor   = new Color(153,153,255);
        
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        bookselling = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkstock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saleshistory = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookreturn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("snebookstore");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bookselling.setBackground(new java.awt.Color(0, 0, 204));
        bookselling.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                booksellingMouseMoved(evt);
            }
        });
        bookselling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksellingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booksellingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booksellingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                booksellingMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Selling");

        javax.swing.GroupLayout booksellingLayout = new javax.swing.GroupLayout(bookselling);
        bookselling.setLayout(booksellingLayout);
        booksellingLayout.setHorizontalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksellingLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        booksellingLayout.setVerticalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksellingLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        checkstock.setBackground(new java.awt.Color(0, 0, 204));
        checkstock.setPreferredSize(new java.awt.Dimension(137, 29));
        checkstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkstockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkstockMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Check Stock");

        javax.swing.GroupLayout checkstockLayout = new javax.swing.GroupLayout(checkstock);
        checkstock.setLayout(checkstockLayout);
        checkstockLayout.setHorizontalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        checkstockLayout.setVerticalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        saleshistory.setBackground(new java.awt.Color(0, 0, 204));
        saleshistory.setPreferredSize(new java.awt.Dimension(137, 29));
        saleshistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleshistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleshistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleshistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saleshistoryMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sales History");

        javax.swing.GroupLayout saleshistoryLayout = new javax.swing.GroupLayout(saleshistory);
        saleshistory.setLayout(saleshistoryLayout);
        saleshistoryLayout.setHorizontalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleshistoryLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        saleshistoryLayout.setVerticalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleshistoryLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );

        logout.setBackground(new java.awt.Color(0, 0, 204));
        logout.setPreferredSize(new java.awt.Dimension(137, 29));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        bookreturn.setBackground(new java.awt.Color(0, 0, 204));
        bookreturn.setPreferredSize(new java.awt.Dimension(137, 29));
        bookreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookreturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookreturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookreturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookreturnMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book Return");

        javax.swing.GroupLayout bookreturnLayout = new javax.swing.GroupLayout(bookreturn);
        bookreturn.setLayout(bookreturnLayout);
        bookreturnLayout.setHorizontalGroup(
            bookreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookreturnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        bookreturnLayout.setVerticalGroup(
            bookreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookreturnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bookselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(bookreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(checkstock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(saleshistory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkstock, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleshistory, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEN BOOK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
        LoginPg1 lp1= new LoginPg1();
        lp1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void booksellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

    }//GEN-LAST:event_booksellingMouseClicked

    private void booksellingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        
       BookSelling bs=new BookSelling();
       bs.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_booksellingMousePressed

    private void checkstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        
       CheckStock cs=new CheckStock();
       cs.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_checkstockMousePressed

    private void saleshistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);
        
       SalesHistory sh=new SalesHistory();
       sh.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_saleshistoryMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
    }//GEN-LAST:event_logoutMousePressed

    private void booksellingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(TouchColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseEntered

    private void booksellingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseExited

    private void checkstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(TouchColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseEntered

    private void checkstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseExited

    private void saleshistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(TouchColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseEntered

    private void saleshistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(TouchColor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_logoutMouseExited

    private void checkstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseClicked

    private void saleshistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseClicked

    private void booksellingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseMoved

    }//GEN-LAST:event_booksellingMouseMoved

    private void bookreturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturnMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(TouchColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturnMouseEntered

    private void bookreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturnMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturnMouseExited

    private void bookreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturnMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        
       BookReturn br=new BookReturn();
       br.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bookreturnMouseClicked

    private void bookreturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookreturnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunctionSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookreturn;
    private javax.swing.JPanel bookselling;
    private javax.swing.JPanel checkstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel saleshistory;
    // End of variables declaration//GEN-END:variables
}
