/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package snebookstoreinventorymanagement;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class ReturnQuantity extends javax.swing.JFrame {

    /**
     * Creates new form ReturnQuantity
     */
    Color DefaultColor,ClickedColor,TouchColor;
    
    public ReturnQuantity() {
        initComponents();
        DefaultColor = new Color(51,153,255);
        ClickedColor = new Color(242,242,242);
        TouchColor   = new Color(153,255,255);
        
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        bookselling = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkstock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saleshistory = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookreturn3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        confirm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setPreferredSize(new java.awt.Dimension(137, 397));

        bookselling.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                booksellingMouseMoved(evt);
            }
        });
        bookselling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksellingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booksellingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booksellingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                booksellingMousePressed(evt);
            }
        });

        jLabel1.setText("Book selling");

        javax.swing.GroupLayout booksellingLayout = new javax.swing.GroupLayout(bookselling);
        bookselling.setLayout(booksellingLayout);
        booksellingLayout.setHorizontalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksellingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        booksellingLayout.setVerticalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksellingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        checkstock.setPreferredSize(new java.awt.Dimension(137, 29));
        checkstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkstockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkstockMousePressed(evt);
            }
        });

        jLabel2.setText("Check stock");

        javax.swing.GroupLayout checkstockLayout = new javax.swing.GroupLayout(checkstock);
        checkstock.setLayout(checkstockLayout);
        checkstockLayout.setHorizontalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkstockLayout.setVerticalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkstockLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        saleshistory.setPreferredSize(new java.awt.Dimension(137, 29));
        saleshistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleshistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleshistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleshistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saleshistoryMousePressed(evt);
            }
        });

        jLabel4.setText("Sales history");

        javax.swing.GroupLayout saleshistoryLayout = new javax.swing.GroupLayout(saleshistory);
        saleshistory.setLayout(saleshistoryLayout);
        saleshistoryLayout.setHorizontalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleshistoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saleshistoryLayout.setVerticalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleshistoryLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        logout.setPreferredSize(new java.awt.Dimension(137, 29));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        jLabel5.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        bookreturn3.setPreferredSize(new java.awt.Dimension(137, 29));
        bookreturn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookreturn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookreturn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookreturn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookreturn3MousePressed(evt);
            }
        });

        jLabel10.setText("Book Return");

        javax.swing.GroupLayout bookreturn3Layout = new javax.swing.GroupLayout(bookreturn3);
        bookreturn3.setLayout(bookreturn3Layout);
        bookreturn3Layout.setHorizontalGroup(
            bookreturn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookreturn3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookreturn3Layout.setVerticalGroup(
            bookreturn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookreturn3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookselling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(checkstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saleshistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookreturn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(bookselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookreturn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleshistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEN BOOK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Book Name", "Author", "Quantity Buy", "Return Quantity", "Reason"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmMousePressed(evt);
            }
        });

        jLabel7.setText("Confirm");

        javax.swing.GroupLayout confirmLayout = new javax.swing.GroupLayout(confirm);
        confirm.setLayout(confirmLayout);
        confirmLayout.setHorizontalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        confirmLayout.setVerticalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMousePressed
        boolean allInputsValid = true;                                          // Flag to track if all input quantities are valid
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/snebookstore", "root", "admin");
            Statement s = con.createStatement();

            LocalDate currentDate = LocalDate.now();                            // Get current date
            String returndate = currentDate.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();   // Iterate through the rows of jTable1
            int row = model.getRowCount();
            for (int i = 0; i < row; i++)
            {                                                                   // Retrieve data from jTable1
                String bookName = (String) model.getValueAt(i, 1);
                String qb =(String) model.getValueAt(i,3);                      // Quantity bought
                String rs = (String) model.getValueAt(i, 4);                    // Return quantity
                String reason = (String) model.getValueAt(i,5);                 // Reason for return
                int returnQuantity = Integer.parseInt(rs);
                int purchaseQuantity = Integer.parseInt(qb);
                if (returnQuantity <=purchaseQuantity)                          // Check if return quantity exceeds purchase quantity
                { 
                    float price = calculateBookPrice(bookName);                 // Calculate book price

                    String insertReturnRecordQuery = "INSERT INTO returnrecord (returnPrice, returnDate) VALUES (" + (price * returnQuantity) + ", '" + returndate + "')";
                    s.executeUpdate(insertReturnRecordQuery);                   // Insert return record into returnrecord table

                    String bookId = getBookIdFromName(bookName);                // Get book ID from book name

                    String insertBookReturnQuery = "INSERT INTO bookreturn (returnid, bookid, reason, returnQuantity) VALUES (LAST_INSERT_ID(),'" + bookId + "', '" + reason + "', " + returnQuantity + ")";
                    s.executeUpdate(insertBookReturnQuery);                     // Insert return record into bookreturn table

                    String updateBookInfoQuery = "UPDATE bookinfo SET quantity = quantity + " + returnQuantity + " WHERE bookid = '" + bookId + "'";
                    s.executeUpdate(updateBookInfoQuery);                       // Update book quantity in bookinfo table
                }
                else 
                    {
                        JOptionPane.showMessageDialog(null, "Return quantity cannot exceed purchase quantity for book: " + bookName, "Error", JOptionPane.ERROR_MESSAGE);
                        allInputsValid = false;
                    }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (allInputsValid)                                                     // Check if all input quantities are valid
        {
            JOptionPane.showMessageDialog(null, "Return records inserted successfully into the database.");
            BookReturn br = new BookReturn();                                   // Switch to BookReturn frame
            br.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_confirmMousePressed

    private void bookreturn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MousePressed

    }//GEN-LAST:event_bookreturn3MousePressed

    private void bookreturn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturn3MouseExited

    private void bookreturn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(TouchColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturn3MouseEntered

    private void bookreturn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        BookReturn br=new BookReturn();
        br.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookreturn3MouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(TouchColor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
        LoginPg1 lp1= new LoginPg1();
        lp1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void saleshistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);

        SalesHistory sh=new SalesHistory();
        sh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saleshistoryMousePressed

    private void saleshistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseExited

    private void saleshistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(TouchColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseEntered

    private void saleshistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseClicked

    private void checkstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        CheckStock cs=new CheckStock();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkstockMousePressed

    private void checkstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseExited

    private void checkstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(TouchColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseEntered

    private void checkstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseClicked

    private void booksellingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        BookSelling bs=new BookSelling();
        bs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_booksellingMousePressed

    private void booksellingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseExited
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseExited

    private void booksellingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(TouchColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseEntered

    private void booksellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseClicked

    private void booksellingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseMoved

    }//GEN-LAST:event_booksellingMouseMoved

private String getBookIdFromName(String bookName) 
{
    String bookId = "";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/snebookstore", "root", "admin");
        Statement statement = con.createStatement();
        String query = "SELECT bookId FROM bookinfo WHERE bookName = '" + bookName + "'";           // Query to retrieve book ID based on book name
        ResultSet bookRs = statement.executeQuery(query);
        if (bookRs.next())                                                                          // If book ID is found, assign it to bookId variable
        {
            bookId = bookRs.getString("bookid");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    return bookId;                                                                                  // Return the book ID
}

private float calculateBookPrice(String bookName) {
    float price = 0.0f;                                                                             // Initialize price variable
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/snebookstore", "root", "admin");
        Statement statement = con.createStatement();
        String query = "SELECT sPrice FROM bookinfo WHERE bookName = '" + bookName + "'";           // Query to retrieve the selling price of the book based on its name
        ResultSet rs = statement.executeQuery(query);
            if (rs.next()) 
            {                                                                                       // If selling price is found, assign it to the price variable
                price = rs.getFloat("sprice");
            }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    return price;                                                                                   // Return the price of the book
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnQuantity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookreturn3;
    private javax.swing.JPanel bookselling;
    private javax.swing.JPanel checkstock;
    private javax.swing.JPanel confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel saleshistory;
    // End of variables declaration//GEN-END:variables
}
