/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package snebookstoreinventorymanagement;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class salesquantity extends javax.swing.JFrame {

    /**
     * Creates new form salesquantity
     */
    Color DefaultColor,ClickedColor,TouchColor;
    public salesquantity() {
        initComponents();
         DefaultColor = new Color(51,153,255);
        ClickedColor = new Color(242,242,242);
        TouchColor   = new Color(153,255,255);
        
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        bookselling = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkstock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saleshistory = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookreturn3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setPreferredSize(new java.awt.Dimension(137, 397));

        bookselling.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                booksellingMouseMoved(evt);
            }
        });
        bookselling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksellingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booksellingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booksellingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                booksellingMousePressed(evt);
            }
        });

        jLabel1.setText("Book selling");

        javax.swing.GroupLayout booksellingLayout = new javax.swing.GroupLayout(bookselling);
        bookselling.setLayout(booksellingLayout);
        booksellingLayout.setHorizontalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksellingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        booksellingLayout.setVerticalGroup(
            booksellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksellingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        checkstock.setPreferredSize(new java.awt.Dimension(137, 29));
        checkstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkstockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkstockMousePressed(evt);
            }
        });

        jLabel2.setText("Check stock");

        javax.swing.GroupLayout checkstockLayout = new javax.swing.GroupLayout(checkstock);
        checkstock.setLayout(checkstockLayout);
        checkstockLayout.setHorizontalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkstockLayout.setVerticalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkstockLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        saleshistory.setPreferredSize(new java.awt.Dimension(137, 29));
        saleshistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleshistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleshistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleshistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saleshistoryMousePressed(evt);
            }
        });

        jLabel4.setText("Sales history");

        javax.swing.GroupLayout saleshistoryLayout = new javax.swing.GroupLayout(saleshistory);
        saleshistory.setLayout(saleshistoryLayout);
        saleshistoryLayout.setHorizontalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleshistoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saleshistoryLayout.setVerticalGroup(
            saleshistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleshistoryLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        logout.setPreferredSize(new java.awt.Dimension(137, 29));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        jLabel5.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        bookreturn3.setPreferredSize(new java.awt.Dimension(137, 29));
        bookreturn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookreturn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookreturn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookreturn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookreturn3MousePressed(evt);
            }
        });

        jLabel10.setText("Book Return");

        javax.swing.GroupLayout bookreturn3Layout = new javax.swing.GroupLayout(bookreturn3);
        bookreturn3.setLayout(bookreturn3Layout);
        bookreturn3Layout.setHorizontalGroup(
            bookreturn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookreturn3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookreturn3Layout.setVerticalGroup(
            bookreturn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookreturn3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookselling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(checkstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saleshistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookreturn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(bookselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookreturn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleshistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEN BOOK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Book Author", "Book Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel7.setText("Confirm");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        jLabel6.setText("Back");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void booksellingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseMoved

    }//GEN-LAST:event_booksellingMouseMoved

    private void booksellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseClicked

    private void booksellingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(TouchColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseEntered

    private void booksellingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMouseExited
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_booksellingMouseExited

    private void booksellingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksellingMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        BookSelling bs=new BookSelling();
        bs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_booksellingMousePressed

    private void checkstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseClicked

    private void checkstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(TouchColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseEntered

    private void checkstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_checkstockMouseExited

    private void checkstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkstockMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(ClickedColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        CheckStock cs=new CheckStock();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkstockMousePressed

    private void saleshistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseClicked

    private void saleshistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(TouchColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseEntered

    private void saleshistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_saleshistoryMouseExited

    private void saleshistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleshistoryMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);

        SalesHistory sh=new SalesHistory();
        sh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saleshistoryMousePressed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
        LoginPg1 lp1= new LoginPg1();
       lp1.setVisible(true);
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(TouchColor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
    }//GEN-LAST:event_logoutMousePressed

    private void bookreturn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseClicked
        // TODO add your handling code here:
        bookselling.setBackground(DefaultColor);
        bookreturn3.setBackground(ClickedColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);

        BookReturn br=new BookReturn();
        br.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookreturn3MouseClicked

    private void bookreturn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseEntered
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(TouchColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturn3MouseEntered

    private void bookreturn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MouseExited
        // TODO add your handling code here:
        bookselling.setBackground(ClickedColor);
        bookreturn3.setBackground(DefaultColor);
        checkstock.setBackground(DefaultColor);
        saleshistory.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }//GEN-LAST:event_bookreturn3MouseExited

    private void bookreturn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreturn3MousePressed

    }//GEN-LAST:event_bookreturn3MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed

    }//GEN-LAST:event_jLabel7MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
     TableModel model1 = jTable1.getModel();                                    // Get the table model from jTable1
    int[] selectedRows = jTable1.getSelectedRows();                             // Get the selected rows from jTable1

    totalprice frm2 = new totalprice();                                         // Create an instance of the totalprice frame
    DefaultTableModel model2 = (DefaultTableModel) frm2.jTable1.getModel();

    int rowCount = model1.getRowCount();                                        // Get the row count of the table model
    float totalPrice = 0;                                                       // Initialize the total price variable

    boolean allValidNumbers = true;                                              // Flag to track if all numbers are valid
    for (int i = 0; i < rowCount; i++) 
    {
        String bookId = (String) model1.getValueAt(i, 0);
        String bookName = (String) model1.getValueAt(i, 1);
        String bookAuthor = (String) model1.getValueAt(i, 2);
        String bookPriceStr = (String) model1.getValueAt(i, 3);
        String quantityStr = (String) model1.getValueAt(i, 4);

        if (isValidNumber(quantityStr))                                         //Check if the quantity is a valid number
        {
            int quantity = Integer.parseInt(quantityStr);                       // Parse quantity string to integer
            if (quantity >= 0)                                                  // Check if quantity is non-negative
            {
                int stockQuantity = getStockQuantityFromDatabase(bookId);       // Get the stock quantity from the database
                if (stockQuantity >= quantity)                                  // Check if there's enough stock
                {
                    float bookPrice = Float.parseFloat(bookPriceStr);           // Check if there's enough stock
                    float subPrice = bookPrice * quantity;                      // Calculate subtotal price
                    totalPrice += subPrice;                                     // Update total price
                    Object[] rowData = {bookId, bookName, bookAuthor, bookPriceStr, quantityStr, subPrice}; // Create row data array
                    model2.addRow(rowData);
                }else
                    {
                         JOptionPane.showMessageDialog(null, "Not enough stock for book: " + bookName, "Stock Warning", JOptionPane.WARNING_MESSAGE);
                         allValidNumbers = false;                               // Set flag to false
                    }
            } 
        } else 
            {
                JOptionPane.showMessageDialog(null, "Please enter valid number!", "Error", JOptionPane.WARNING_MESSAGE);
                allValidNumbers = false;                                        // Set flag to false
            }
    }
    
    if(allValidNumbers)                                                         // If all numbers are valid
    {
        frm2.jTable1.setModel(model2);
        frm2.total.setText(String.valueOf(totalPrice));
        frm2.setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_jPanel3MousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        BookSelling br=new BookSelling();
        br.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMousePressed

    public static int getStockQuantityFromDatabase(String bookId)
    {
        int stockQuantity =0;                                                   // Initialize stock quantity to 0
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/snebookstore", "root", "admin");
            Statement s = con.createStatement();
            
            String query ="SELECT quantity FROM bookinfo WHERE bookid ='"+ bookId +"'"; // Execute query to retrieve quantity from bookinfo table
            ResultSet resultSet=s.executeQuery(query);
            
                if(resultSet.next())                                             // If result set has a row, retrieve quantity and assign to stockQuantity
                {
                    stockQuantity = resultSet.getInt("quantity");
                }
        }catch(Exception ex)
            {
                ex.printStackTrace();
            }
        return stockQuantity;                                                   // Return the stock quantity of the book
    }
    
private boolean isValidNumber(String str) 
{
    if (str == null || str.isEmpty()) {
        return false;
    }
    return str.matches("\\d+");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesquantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesquantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesquantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesquantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesquantity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JPanel bookreturn3;
    private javax.swing.JPanel bookselling;
    private javax.swing.JPanel checkstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel saleshistory;
    // End of variables declaration//GEN-END:variables
}
